### ISSUE TITLE
keyvaults are created in UK South

### ISSUE THREAD

**Issue by mucifous** [microsoft/dstoolkit-mlops-databricks#29]
I have been trying to debug the API failing due to bad PATs.  I just noticed noticed that in all of the databricks resource groups, everything is in US East except the vaults. Is this correct?
![image](https://user-images.githubusercontent.com/2728534/211870641-ddf48875-5c78-457f-b48c-73c18ba28b43.png)

**Comment by mucifous** [comment]
hard coded in https://github.com/microsoft/dstoolkit-mlops-databricks/blob/main/.github/MLOps_Engineer/Infrastructure/Az_Resources/Az_KeyVault/Az_KeyVault.bicep

**Comment by mucifous** [comment]
after removing ```
location: "ukwest"
```
 (line 9?)

everything worked and I have been able to fully deploy using your accelerator.  
![Screenshot 2023-01-11 154454](https://user-images.githubusercontent.com/2728534/211914961-9d4fbbcc-e6ba-41a4-bdae-e3e1dd26a0af.png)

**Comment by ciaran28** [comment]
Hi @mucifous apologies in the late response in getting back to you. Unfortunately I missed your comment!

Thank you for trouble shooting this issue, and resolving. I will update the code this week to ensure all resource locations are consistent to ensure this issue does not affect others

**Comment by mucifous** [comment]
No worries! I really appreciate this accelerator and intend to continue working with it as a primary pattern in our ml processes.
